### PR TITLE
Switch from npub to nlm

### PR DESCRIPTION
**Pull request by jkrems**

### CODE REVIEW

**Comment by ageitgey** [comment]
The change itself looks fine to me. But it is a tiny bit weird that you upgraded to node 4.2 and changed the license in a chore about switching to nlm.

**Comment by jkrems** [comment]
The previous name "BSD-2" actually didn't match the `LICENSE` file (and thus also not the file headers). The upgrade to node 4.2 is needed for `nlm` since it requires node 4. We can make it a major bump and officially drop node 0.10 support.

**Comment by jkrems** [comment]
Now marked as `semver-major`.

**Comment by ageitgey** [comment]
LGTM

**Pull request merged**
